config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only: %i[edit] do
    resources :elements, except: %i[index] do
      member do
        patch :move
      end
    end
  end

  resources :profiles, only: %i[edit update]
  resources :themes, only: %i[edit update]

  post 'flash', to: 'flash#dismiss'
  get ':id', to: 'users#show', as: 'username'

  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/element.rb
class Element < ApplicationRecord
  acts_as_list

  belongs_to :page
end

app/models/page.rb
class Page < ApplicationRecord
  # 
  belongs_to :user

  has_one :theme, dependent: :destroy
  has_many :elements, dependent: :destroy

  after_create do
    create_theme 
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar
end

app/models/theme.rb
class Theme < ApplicationRecord
  belongs_to :page
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :page, dependent: :destroy
  has_one :profile, dependent: :destroy

  validates :username, uniqueness: true

  after_create do
    create_page
    create_profile
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    edit_page_path(current_user.page.id)
  end

  protected

  def configure_permitted_parameters
    added_attrs = %i[username email password password_confirmation remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: %i[login password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page
  before_action :set_element, only: %i[edit update destroy move]

  def new
    @element = @page.elements.build(element_type: params[:element_type])
  end

  def edit; end

  def create
    @element = @page.elements.build(element_params)
    # @element.position = 1 + (@page.elements.maximum(:position) || 0)

    respond_to do |format|
      if @element.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @element.update(element_params)
        format.turbo_stream
        format.html do
          redirect edit_page_path(@page), notice: "#{@element.element_type.capitalize} was successfully updated."
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @element.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  def move
    @element.insert_at(params[:position].to_i)
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_page
    @page = Page.find(params[:page_id])
  end

  def set_element
    @element = @page.elements.find(params[:id])
  end

  def element_params
    params.require(:element).permit(
      :element_type,
      :title,
      :url,
      :twitter_handle,
      :youtube,
      :position,
      :page_id
    )
  end
end

app/controllers/flash_controller.rb
class FlashController < ApplicationController
  def dismiss
    flash.clear
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page

  def edit; end

  private

  def set_page
    @page = Page.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile

  def edit; end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.turbo_stream
        format.html do
          redirect edit_page_path(@profile.user.page), notice: 'Profile was successfully updated.'
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:display_name, :bio, :user_id, :avatar)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_theme

  def edit  
  end

  def update
    if @theme.update(theme_params)
      redirect_to edit_page_path(@theme.page)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

    def theme_params
      params.require(:theme).permit(:background_color, :button_color, :text_color, :page_id)
    end

    def set_theme
      @theme = Theme.find_or_create_by(page_id: params[:page_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'public'
  def show
    @user = User.find_by(username: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/element_helper.rb
module ElementHelper
end

app/helpers/pages_helper.rb
module PagesHelper

  def background_color(bg_color = "#FFFFFF")
    bg_color
  end

  def button_color(bg_color = "#FFFFFF")
    bg_color
  end

  def text_color(tx_color = "#000000")
    tx_color
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/elements/_link.html.erb
<div data-id="<%= element.id %>">
  <%= turbo_frame_tag dom_id(element) do %>
      <div class="card card-side w-full bg-base-100 shadow mt-2">
        <div class="handle flex items-center bg-slate-100 hover:cursor-grabbing hover:bg-slate-200 hover:text-blue-600">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 15L12 18.75 15.75 15m-7.5-6L12 5.25 15.75 9" />
          </svg>
        </div>
        <div class="card-body">
          <h4 class="font-bold"><%= element.title %></h4>
          <p><%= element.url %></p>
          <div class="flex w-full justify-end" >
            <%= link_to edit_page_element_path(element.page, element) do %>      
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
              </svg>
            <% end %>
            <%= button_to page_element_path(element, page_id: element.page_id), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } do %>      
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-red-600">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
              </svg>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>
</div>

app/views/elements/_link_form.html.erb
<div class="card w-full bg-base-100 shadow mt-2">
  <div class="card-body">
    <%= form_with(model: [page, element]) do |form| %>
      <%= form.hidden_field :element_type, value: 'link' %>
      <div>
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, class: "input input-bordered w-full max-w-xs", placeholder: "Enter title"  %>
      </div>
      <div>
        <%= form.label :url, class: "label" %>
        <%= form.text_field :url, class: "input input-bordered w-full max-w-xs", placeholder: "Enter URL" %>
      </div>
      <div class="card-actions justify-end">
        <%= link_to "Cancel", edit_page_path(page), class: "btn btn-outline mr-2" %>
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/elements/_twitter.html.erb
<div data-id="<%= element.id %>">
  <%= turbo_frame_tag dom_id(element) do %>
    <div class="card card-side w-full bg-base-100 shadow mt-2">
      <div class="handle flex items-center bg-slate-100 hover:cursor-grabbing hover:bg-slate-200 hover:text-blue-600">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 15L12 18.75 15.75 15m-7.5-6L12 5.25 15.75 9" />
        </svg>
      </div>
      <div class="card-body">
        <h4 class="font-bold">Twitter Username</h4>
        <p><%= element.twitter_handle %></p>
        <div class="flex w-full justify-end" >
          <%= link_to edit_page_element_path(element.page, element) do %>      
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
            </svg>
          <% end %>
          <%= button_to page_element_path(element, page_id: element.page_id), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } do %>      
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-red-600">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/elements/_twitter_form.html.erb
<div class="card w-full bg-base-100 shadow mt-2">
  <div class="card-body">
    <%= form_with(model: [page, element]) do |form| %>
      <%= form.hidden_field :element_type, value: 'twitter' %>
      <div>
        <%= form.label "What is your Twitter Username", class: "label" %>
        <%= form.text_field :twitter_handle, class: "input input-bordered w-full max-w-xs", placeholder: "Enter title"  %>
      </div>
      <div class="card-actions justify-end">
        <%= link_to "Cancel", edit_page_path(page), class: "btn btn-outline mr-2" %>
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/elements/_youtube.html.erb
<div data-id="<%= element.id %>">
  <%= turbo_frame_tag dom_id(element) do %>
    <div class="card card-side w-full bg-base-100 shadow mt-2">
      <div class="handle flex items-center bg-slate-100 hover:cursor-grabbing hover:bg-slate-200 hover:text-blue-600">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
          <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 15L12 18.75 15.75 15m-7.5-6L12 5.25 15.75 9" />
        </svg>
      </div>
      <div class="card-body">
        <h4 class="font-bold"><%= element.title %></h4>
        <p><%= element.youtube %></p>
        <div class="flex w-full justify-end" >
          <%= link_to edit_page_element_path(element.page, element) do %>      
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2">
              <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
            </svg>
          <% end %>
          <%= button_to page_element_path(element, page_id: element.page_id), method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } do %>      
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 text-red-600">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
            </svg>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/elements/_youtube_form.html.erb
<div class="card w-full bg-base-100 shadow mt-2">
  <div class="card-body">
    <%= form_with(model: [page, element]) do |form| %>
      <%= form.hidden_field :element_type, value: 'youtube' %>
      <div>
        <%= form.label :title, class: "label" %>
        <%= form.text_field :title, class: "input input-bordered w-full max-w-xs", placeholder: "Enter title"  %>
      </div>
      <div>
        <%= form.label "Enter Share URL", class: "label" %>
        <%= form.text_field :youtube, class: "input input-bordered w-full max-w-xs", placeholder: "Enter title"  %>
      </div>
      <div class="card-actions justify-end">
        <%= link_to "Cancel", edit_page_path(page), class: "btn btn-outline mr-2" %>
        <%= form.submit "Save", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/elements/create.turbo_stream.erb
<%= turbo_stream.append "elements-list", partial: "elements/#{@element.element_type}", locals: { element: @element } %>
<%= turbo_stream.append "preview-elements", partial: "pages/elements/#{@element.element_type}", locals: { element: @element, page: @element.page } %>
<%= turbo_stream.update "new-element" %>

app/views/elements/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@element) %>
<%= turbo_stream.remove "preview-#{dom_id(@element)}" %>

app/views/elements/edit.html.erb
<h1>Element#edit</h1>
<p>Find me in app/views/element/edit.html.erb</p>

app/views/elements/move.turbo_stream.erb
<%= turbo_stream.replace "preview_#{dom_id(@page)}", partial: "pages/preview" %>

app/views/elements/new.html.erb
<%= turbo_frame_tag "new-element" do %>
  <%= render "elements/#{@element.element_type}_form", page: @page, element: @element %>
<% end %>

app/views/elements/update.html.erb
<h1>Element#update</h1>
<p>Find me in app/views/element/update.html.erb</p>

app/views/elements/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@element), partial: "elements/#{@element.element_type}", locals: { element: @element } %>
<%= turbo_stream.update "preview-#{dom_id(@element)}", partial: "pages/elements/#{@element.element_type}", locals: { element: @element, page: @element.page } %>

app/views/flash/dismiss.turbo_stream.erb
<%= turbo_stream.update "flash-messages", partial: "shared/message" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title>Keepingitsocial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <div id="flash-messages">
      <%= render 'shared/message' %>
    </div>
     <%= yield %>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title>Keepingitsocial</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body style="background-color:<%= background_color(@user.page.theme.background_color) %>">
     <%= yield %>
     <div class="w-full text-center">  
      <%= link_to "Keeping It Social", root_path, class: "btn btn-ghost normal-case text-xl" %>
     </div>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
  </body>
</html>

app/views/pages/_preview.html.erb
<%= turbo_frame_tag "preview_#{dom_id(@page)}" do %>
  <div class="my-2 relative" data-controller="clipboard">
    <span class="hidden absolute bottom-0 right-0 bg-green-300 rounded px-2 py-1" data-clipboard-target="tooltip">Copied!</span>
    <%= link_to "#{username_url(@page.user.username)}", username_path(@page.user.username), data: { turbo_frame: "_top", clipboard_target: "source" }, class: "link" %>
    <button data-action="clipboard#copy">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 7.5V6.108c0-1.135.845-2.098 1.976-2.192.373-.03.748-.057 1.123-.08M15.75 18H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08M15.75 18.75v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0 01-1.125-1.125v-1.5A3.375 3.375 0 006.375 7.5H5.25m11.9-3.664A2.251 2.251 0 0015 2.25h-1.5a2.251 2.251 0 00-2.15 1.586m5.8 0c.065.21.1.433.1.664v.75h-6V4.5c0-.231.035-.454.1-.664M6.75 7.5H4.875c-.621 0-1.125.504-1.125 1.125v12c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V16.5a9 9 0 00-9-9z" />
      </svg>
    </button>
  </div>
  <div class="artboard phone-1 rounded-3xl border border-gray-800 overflow-y-auto" style="background-color:<%= background_color(@page.theme.background_color) %>">
    <div class="m-6 text-center">
      <%= turbo_frame_tag "preview-#{dom_id(@page.user.profile)}" do %>
        <%= render "pages/elements/profile", profile: @page.user.profile, page: @page %>
      <% end %>
      <%= turbo_frame_tag "preview-elements" do %>
        <% @page.elements.order(position: :asc).each do |element| %>
          <%= render "pages/elements/#{element.element_type}", element: element, page: @page %>
        <% end %>
      <% end %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div class="flex bg-gray-100">
  <div class="overflow-y-auto h-screen w-full border-r border-gray-300 pt-20 px-4 mr-auto">
    <%= link_to "Link", new_page_element_path(@page, element_type: "link"), data: { turbo_frame: "new-element" } , class: "btn btn-outline" %>
    <%= link_to "Twitter Feed", new_page_element_path(@page, element_type: "twitter"), data: { turbo_frame: "new-element" } , class: "btn btn-outline" %>
    <%= link_to "Youtube Video", new_page_element_path(@page, element_type: "youtube"), data: { turbo_frame: "new-element" } , class: "btn btn-outline" %>
    <%= render "profiles/profile", profile: @page.user.profile %>
    <div class="divider"></div>
    <%= turbo_frame_tag "elements-list", data: { controller: "drag", drag_url_value: "/pages/#{@page.id}/elements/:id/move" } do %>
      <% @page.elements.order(position: :asc).each do |element| %>
        <%= render "elements/#{element.element_type}", element: element %>
      <% end %>
    <% end %>
    <%= turbo_frame_tag "new-element" %>
  </div>
  <div id="preview" class="hidden md:block pt-20 px-8">
    <%= render "preview" %>
  </div>
</div>

app/views/profiles/_profile.html.erb
<%= turbo_frame_tag dom_id(profile) do %>
  <div class="card card-side w-full bg-base-100 shadow mt-4">
    <div class="card-body">
      <h4 class="font-bold"><%= profile.display_name ||= "Profile" %></h4>
      <p><%= profile.bio %></p>
      <div class="flex w-full justify-end" >
        <%= link_to edit_profile_path(profile) do %>      
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5 mr-2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
          </svg>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_message.html.erb
<% flash.each do |name, msg| %>
  <div class="flex justify-between pt-20 pb-4 px-4 mb-4 bg-blue-100 border-t-4 border-blue-500 dark:bg-blue-200" role="alert">
    <div class="flex">
      <svg class="flex-shrink-0 w-5 h-5 text-blue-700" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
      <div class="ml-3 text-sm font-medium text-blue-700">
        <%= msg %>
      </div>
    </div>
    <%= button_to flash_path, class: " -mx-1.5 -my-1.5 bg-blue-100 dark:bg-blue-200 text-blue-500 rounded-lg focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200 dark:hover:bg-blue-300 inline-flex h-8 w-8" do %>
      <span class="sr-only">Dismiss</span>
      <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
    <% end %>
  </div>
<% end %>

app/views/shared/_navigation.html.erb
<div class="fixed navbar bg-base-100 z-50">
  <div class="navbar-start">
    <% if user_signed_in? %>
    <div class="dropdown">
      <label tabindex="0" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
      </label>
      <% if user_signed_in? %>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
          <li><%= link_to "Page", edit_page_path(current_user.page) %></li>
          <li><%= link_to "Theme", edit_theme_path(current_user.page.theme, page_id: current_user.page.id) %></li>
        </ul>
      <% end %>
    </div>
    <% end %>
    <%= link_to "Keeping It Social", root_path, class: "btn btn-xs btn-ghost sm:btn-md font-bold" %>
  </div>
  <div class="navbar-center hidden lg:flex">
    <% if user_signed_in? %>
      <ul class="menu menu-horizontal p-0">
        <li><%= link_to "Page", edit_page_path(current_user.page) %></li>
        <li><%= link_to "Theme", edit_theme_path(current_user.page.theme, page_id: current_user.page.id) %></li>
      </ul>
    <% end %>
  </div>
  <div class="navbar-end">
    <% if user_signed_in? %>
      <div class="mr-4 badge badge-primary">
        <%= current_user.username.capitalize || current_user.email %>
      </div>
      <%= button_to "Log out", destroy_user_session_path , method: :delete, data: { turbo: "false" }, class: "btn btn-xs btn-outline sm:btn-md mr-3" %>
    <% else %>
      <%= link_to "Log in", new_user_session_path, class: "btn btn-xs btn-outline sm:btn-md mr-3" %>
      <%= link_to "Get Started", new_user_registration_path, class: "btn btn-xs sm:btn-md" %>
    <% end %>
  </div>
</div>

app/views/themes/_form.html.erb
<div class="pt-20 px-10 w-1/2">
  <%= form_with(model: theme, url: theme_path(theme, page_id: theme.page_id)) do |form| %>
    <div>
      <%= form.label :background_color, class: "label" %>
      <%= form.color_field :background_color, class: "input input-bordered w-full max-w-xs" %>
    </div>
    <div>
      <%= form.label :button_color, class: "label" %>
      <%= form.color_field :button_color, class: "input input-bordered w-full max-w-xs" %>
    </div>
    <div>
      <%= form.label :text_color, class: "label" %>
      <%= form.color_field :text_color, class: "input input-bordered w-full max-w-xs" %>
    </div>
    <div class="card-actions mt-2">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/themes/edit.html.erb
<h4>Theme</h4>

<%= render 'form', theme: @theme %>